### ISSUE TITLE
One client makes multiple Handshake&Connect and only removed the last session

### ISSUE THREAD

**Issue by alexmacl** [cometd/cometd#683] opened 2016-10-31 16:43 UTC
Hello! I have a problem and not if it's a bug...

CometD versión: 3.0.10
Jetty versión: 9.2.18.v20160721
CometD client: jQuery

In my CometDInitializer i associate a listener...

`public void init() throws ServletException {
		BayeuxServer bayeux = (BayeuxServer) getServletContext().getAttribute(BayeuxServer.ATTRIBUTE);
		bayeux.addListener(new BayeuxServerSessionListener() {});
	}`

and..,

```
public class BayeuxServerSessionListener implements SessionListener {

	private static final Logger LOG = LoggerFactory.getLogger(BayeuxServerSessionListener.class);

	@Override
	public void sessionAdded(ServerSession session, ServerMessage message) {
		LOG.debug("sessionAdded: " + session.getId() + " (message: " + message.toString() + ")");
	}

	@Override
	public void sessionRemoved(ServerSession session, boolean timeout) {
		LOG.debug("sessionRemoved: " + session.getId() + " (timeout: " + timeout + ")");
	}
}
```

Ok...

Well, if a client from one browser tab, for 3 requests handshake&connect ... I get 3 times the **sessionAdded** event, but... when the client closes the browser, only the last session is deleted (**sessionRemoved** event). Previous 2 sessions remain there "indefinitely"...

This is a bug? How I can control this?

I have simplified the maximum this example to know if this is normal  is it a bug.. .I am aware that the client should not do this, but I want to maintain the consistency of my application even if a customer does not operate correctly.

Thank you very much in advance,
Alex.

**Comment by sbordet** [comment] 2016-10-31 17:06
Could be that 2 sessions are local sessions created by services. You can test this with `ServerSession.isLocalSession()`. `LocalSession` instances do not expire.

**Comment by alexmacl** [comment] 2016-11-02 08:44
Thanks @sbordet,

Unfortunately this is not the case....

If i print all sessions in my server...  I get this:

`callbackSessionsCometDGetJson({
    "sessions": [
        {
            "id": "215y24v36ajulxfuuqokr9ij7",
            "user": "Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/54.0.2840.71 Safari\/537.36",
            "isconnected": true,
            "timeout": 30000,
            "islocalsession": false,
            "ishandshook": true
        },
        {
            "id": "4xbl8h02ds8eh667hidtftuyw",
            "user": "Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/54.0.2840.71 Safari\/537.36",
            "isconnected": true,
            "timeout": 30000,
            "islocalsession": false,
            "ishandshook": true
        },
        {
            "id": "31glpijyeoxka31hvd6tj5ksy30",
            "user": "Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/54.0.2840.71 Safari\/537.36",
            "isconnected": true,
            "timeout": 30000,
            "islocalsession": false,
            "ishandshook": true
        },
        {
            "id": "MYAPPSERVER_11my54fgydpt6xv5gri6gotrqv",
            "isconnected": true,
            "timeout": -1,
            "islocalsession": true,
            "ishandshook": true
        }
    ],
    "success": true,
    "size": 4
});
`


And... if i close client navigator (chrome), only the last session is removed..

`callbackSessionsCometDGetJson({
    "sessions": [
        {
            "id": "215y24v36ajulxfuuqokr9ij7",
            "user": "Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/54.0.2840.71 Safari\/537.36",
            "isconnected": true,
            "timeout": 30000,
            "islocalsession": false,
            "ishandshook": true
        },
        {
            "id": "31glpijyeoxka31hvd6tj5ksy30",
            "user": "Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/54.0.2840.71 Safari\/537.36",
            "isconnected": true,
            "timeout":30000,
            "islocalsession": false,
            "ishandshook": true
        },
        {
            "id": "BIG_11my54fgydpt6xv5gri6gotrqv",
            "isconnected": true,
            "timeout": -1,
            "islocalsession": true,
            "ishandshook": true
        }
    ],
    "success": true,
    "size": 3
});
`

Staying these 2 sessions on the server indefinitely...

Thank you very much in advance,
Alex.

**Comment by sbordet** [comment] 2016-11-02 08:50
How do you exactly create those sessions ? You open 3 tabs ? Are you using Oort ?

Can you please provide exact steps to reproduce the issue ?

**Comment by alexmacl** [comment] 2016-11-02 09:03
Thanks @sbordet ,

I create the sessions with the client Cometd jquery ... all in the same tab (not the right way, but I want to prevent this behavior from the client in my server).

jQuery versión: 2.2.1.min.js

In my web i have a one button that execute this function "handshakeAndSubscribeCometd()". The customer "mistakenly" made 3 times click on that button...


```
var CONSOLE_COMETD = '#consoleCometd';	
var URL_COMETD = "http://....";

function handshakeAndSubscribeCometd() {

	var cometd = $.cometd;

	function _connectionEstablished() {
		$(CONSOLE_COMETD).append('Connection Established<br/>');
	}

	function _connectionBroken() {
		$(CONSOLE_COMETD).append('Connection Broken<br/>');
	}

	function _connectionClosed() {
		$(CONSOLE_COMETD).append('Connection Closed<br/>');
	}

	// Function that manages the connection status with the
	// Bayeux server
	var _connected = false;

	function _metaConnect(message) {
		if (cometd.isDisconnected()) {
			_connected = false;
			_connectionClosed();
			return;
		}
		var wasConnected = _connected;
		_connected = message.successful === true;
		if (!wasConnected && _connected) {
			_connectionEstablished();
		} else if (wasConnected && !_connected) {
			_connectionBroken();
		}
	}

	// Function invoked when first contacting the server and
	// when the server has lost the state of this client
	function _metaHandshake(handshake) {

		// Only subscribe if the handshake is successful
		if (handshake.successful === true) {

			var myChannelSubscribe = 'MYCHANNELNAME';

			// Batch all subscriptions together
			cometd.batch(function() {

				cometd.subscribe(myChannelSubscribe,
					function(message) {
						
						var json = message.data;
						$(CONSOLE_COMETD).append(
								"[" + getTimeStamp() + '] <b>' + json.name
										+ '</b> ' + JSON.stringify(json)
										+ "<br/>");

					},
					function(subscribeReply) {

						if (subscribeReply.successful) {
							$(CONSOLE_COMETD).append(
									"Subscribe to \'" + myChannelSubscribe
											+ "\' ok.<br/>");
						}
						else {
							$(CONSOLE_COMETD).append("ERROR: NOT subscribe to \'"
											+ myChannelSubscribe
											+ "\'.<br/>");
						}

					}
				);

			});
		}
		else {

			var errorHandshake = 'ERROR: handshake failed';

			if (handshake.ext != undefined) {
				errorHandshake += " (handshake.ext=" +  JSON.stringify(handshake.ext) + ")" ;
			}

			$(CONSOLE_COMETD).append(errorHandshake + '.<br/>');
		}
	}

	// Disconnect when the page unloads
	$(window).unload(function() {
		cometd.disconnect(true);
	});

	cometd.configure({
		url : URL_COMETD,
		logLevel : 'debug'
	});

	cometd.websocketEnabled = true;
	cometd.addListener('/meta/handshake', _metaHandshake);
	cometd.addListener('/meta/connect', _metaConnect);

	cometd.handshake();
}

function getTimeStamp() {
	var sdf = new SimpleDateFormat("d MMM yyyy HH:mm:ss:SSS");
	return sdf.format(new Date());
}


```

**Comment by sbordet** [comment] 2016-11-02 09:31
Simple solution for your issue is to avoid handshaking multiple times.
You either have to put the code that configures and handshake on a "load" event so that it's only executed once, or protect the code so that if the `cometd` object is already handshaken, you skip it the second time.

Having said that, I will investigate why handshaking multiple times causes the sessions to linger.

**Comment by alexmacl** [comment] 2016-11-02 09:59
Thanks already @sbordet,

The problem is that my project is a middleware and the client is a 3rd party client... Then I would like to control behavior in case, preventing sessions on my server indefinite stay...

Thank you very much in advance,
Alex.

**Comment by sbordet** [comment] 2016-12-23 16:11
@alexmacl I cannot reproduce. The server sessions are swept after `maxInterval` as expected.

**Comment by sbordet** [comment] 2017-06-08 11:13
Closing, no further activity, cannot reproduce and #695 should prevent this issue to happen.

**Closed by sbordet** 2017-06-08 11:13 UTC
Labels: task
