### ISSUE TITLE
long poll protocol stops polling

### ISSUE THREAD

**Issue by alahammad** [cometd/cometd#1459] opened 2023-07-14 19:58 UTC
CometD version 4.0.4
 
**Description**
We have implementation of cometD in our App (Android/iOS), recently we faced issue, the long poll protocol stops polling when user change network from wifi to mobile network. he can send data but can't receive .
the logs is return success .

**Comment by sbordet** [comment] 2023-07-14 21:40
Sorry, too little information to help you.

Do you have the CometD debug logs that show the problem?
Stack trace?

**Comment by alahammad** [comment] 2023-07-16 05:20
I can't share logs because of employment policy. what i can there is request going from client and response is successful 
the missing /meta/connect stopped sending, means client stop polling messages from server
i am sure i miss configuration for this.

**Comment by alahammad** [comment] 2023-07-16 05:54
part of logs when user change network connection :
[java.net.SocketException: Software caused connection abort, java.net.SocketException: Software caused connection abort, java.net.SocketException: Software caused connection abort, java.net.SocketException: Software caused connection abort, java.net.SocketException: Software caused connection abort]

**Comment by sbordet** [comment] 2023-07-16 08:52
What you can try is to ask iOS/Android to notify you of the network change.
When you get the notification, you call `disconnect()` and you `handshake()` again.

In theory there should be no need to do this, as CometD will catch the `SocketException` and try to open a new connection, which should happen on the new network, so the connection will be seamlessly re-established.

**Comment by alahammad** [comment] 2023-07-16 09:03
Actually cometD it catch Socket exception, only polling request stops. I need a way to start polling from server again, in case user change mobile network or polling stops

**Comment by sbordet** [comment] 2023-07-16 09:45
> Actually cometD it catch Socket exception, only polling request stops.

It is not supposed to stop. We have a large number of tests for this scenario.

You have to provide proof of what's going on, so we can determine whether you are hitting a corner case, and if so we can fix it.

As I said, network interruptions are expected in CometD, there is a configurable retry mechanism, and everything works fine with normal networks and OSes.

I think the problem is more on the mobile side where CometD tries to open a new connection, but iOS/Android still gives CometD the old stack with the old network so when CometD tries to open a new connection it fails.

IIRC, both iOS and Android have ways to communicate network changes, so you can try the workaround I described in a previous comment (disconnect + handshake).

**Comment by sbordet** [comment] 2024-05-29 13:44
No further information, closing.

**Closed as completed by sbordet** 2024-05-29 13:44 UTC
