### ISSUE TITLE
Performance questions

### ISSUE THREAD

**Issue by rahmanusta** [cometd/cometd#781] opened 2018-07-13 09:58 UTC
1) Is there any performance benefit if we use batching for only websocket transport is used?

There should be benefit for other protocols like Long-polling, because it'll push messages in one response and in an array [], instead of many separate messages when batching is enabled. However, when websocket is used, naturally only one connection is used and messages are transferred in frames whatever batching is enabled or disabled.

2) What is the benefit of using lazy messages or channels? What is the benefit of sending a message at T+5 instead of T? Thank you.

**Comment by sbordet** [comment] 2018-07-13 13:40
1. There is a smaller benefit using batching for WebSocket because the implementation may be able to fit more than one CometD message in a WebSocket message. Even if that's not the case, batching could allow fewer TCP writes to send the messages.
Bottom line is that you should not care too much: if you know you have the chance to batch, do it, regardless of the transport.

2. [Lazy messages (or channels)](https://docs.cometd.org/current/reference/#_java_server_lazy_messages) allow the server to gather more messages to send to the client.
Imagine a chat for an important events with possibly million users chatting. Without lazy channels, every time a user sends a message to the chat, your connection to the server would need to be woken up to deliver the message. With so many users, chances are that your connection will be super-busy (there is always a message to deliver) and therefore will continuously poll the server.
With lazy channels, messages to you will be delivered once in a while (e.g. 1-2 or more seconds), reducing the load on the server that is now long-polled only every 1-2 or more seconds.

**Comment by rahmanusta** [comment] 2018-07-13 14:36
1. I got it, however cometD doesn't batch multiple messages into a single Websocket frame when batching is enabled. Do I miss something ?

2. I created a demo to see lazy channel's effect in action
2.1 setLazy=true and setLazyTimeout=10 * 1000
2.2 pushes a message to the connected client on every 10ms
2.3 I expect cometD will collect some several messages and push them in single response, but actually clients makes polling on every 30-40 ms. Is it a correct test approach of this feature?

**Comment by sbordet** [comment] 2018-07-13 15:00
1. Currently it does not on the client (but may do in future), but can do on the server (see parameter `ws.messagesPerFrame` [here](https://docs.cometd.org/current/reference/#_java_server_configuration)).

2. I expect messages to be collected - do you have a reproducible case?

**Comment by sbordet** [comment] 2018-09-04 08:38
Closing since there is no further activity and lazy messages are tested and working as expected.

**Closed by sbordet** 2018-09-04 08:38 UTC
Labels: question
