### ISSUE TITLE
CometD Angular - How to reduce meta/connect requests interval on production

### ISSUE THREAD

**Issue by ddouras** [cometd/cometd#874] opened 2019-09-03 06:58 UTC
I have an issue as stated in https://stackoverflow.com/questions/57766378/cometd-angular-how-to-reduce-meta-connect-requests-interval-on-production. Any ideas how to solve?

**Comment by sbordet** [comment] 2019-09-03 08:31
@ddouras you have to explain in more details what's the difference between your local runs and production.

If the server is continuously streaming events to your client, then the behavior is normal.

**Comment by ddouras** [comment] 2019-09-03 09:26
@sbordet sorry I have to rephrase. Is there any configuration variable or other way to increase the polling interval that cometd uses for the subscription channels (i.e salesforce channel)?

**Comment by sbordet** [comment] 2019-09-03 09:32
@ddouras CometD does not "poll", it "long polls".
The server is configured with the long poll timeout, so there is little you can do from the client.

I think you are looking at this problem in the wrong way: you think the problem is the poll interval, but it's likely something entirely different, such as many messages delivered from the server onto the channels you subscribe.

It would help if you take the client side DEBUG logs and see what's going on.

**Comment by ddouras** [comment] 2019-09-03 09:48
The polling request that happens almost every second is the meta/connect one. This is sent form client to server and I have no messages form server to client

**Comment by sbordet** [comment] 2019-09-03 09:50
@ddouras I need evidence. Attach the DEBUG logs to this issue.

**Comment by ddouras** [comment] 2019-09-03 09:53
![image](https://user-images.githubusercontent.com/30793590/64163292-a6ed1300-ce49-11e9-96d3-06258e7053a6.png)

here's a snapshot from my production app. When I run on production message advice is set to 2000ms but locally it is set 0 for some reason

**Comment by sbordet** [comment] 2019-09-03 10:03
Read this: https://docs.cometd.org/current4/reference/#_multiple_sessions_with_http1_1.

**Comment by sbordet** [comment] 2019-10-07 13:29
@ddouras I think this issue was clarified. If you are good, can you please close the issue?

**Closed as completed** 2019-10-30 09:46 UTC
