### ISSUE TITLE
CometD does not reconnect when 402::unknown client error is received

### ISSUE THREAD

**Issue by qasim9872** [cometd/cometd#1033] opened 2021-04-29 18:03 UTC
Hi,

Thanks for the amazing work on this project.

I am working on integrating Genesys Mobile Services (GMS) with our backend server using Chat V2 CometD API. I am using [cometd-nodejs-client](https://github.com/cometd/cometd-nodejs-client) to patch the CometD library to work on a backend server. I have followed the Genesys sample provided [here](https://docs.genesys.com/Documentation/GMS/8.5.2/ClientSamples/ChatV2CometDWebSocketSample) as the base. 

Occasionally, the GMS server returns the following error code: 402::unknown client. The docs for the sample application provided by Genesys states the following: 

> it means that the /meta/connect request failed. In this scenario, the sample checks for the error received and, if the error code is 402, it processes it as if the Chat Server is disconnected.
> Based on the advice received in the response, the CometD library submits the handshake request again, if needed, and does not require that you take care of it.

In our case, once the 402 error occurs, the chat stops working and no more events are received. This makes me think that unlike what the docs say, the reconnection does not happen?

Looking for some advice or a nudge in the right direction? 

Kind regards,
Qasim

**Comment by sbordet** [comment] 2021-04-29 18:12
> I am using cometd-nodejs-client to patch the CometD library to work on a backend server.

Not sure exactly what that means. Are you using `cometd-nodejs-client` to connect to a backend CometD server?

> 402::unknown client

This means that the server lost that particular CometD session with the client.
This happens when there is a network problem (client cannot communicate with the server for long enough so the server expires the CometD session); it may also happen when the client or the server takes too long to process messages so that CometD sessions are expired -- but it's typically a very rare case.
Also happens if the server has been restarted -- it has lost all the CometD sessions.

What happens after the error depends on the `advice` the server sends back to the client.
The server may ask the client to re-handshake, or to close the connection.

If this is reproducible for you, run with DEBUG logs enabled (see https://docs.cometd.org/current/reference/#_troubleshooting_logging_javascript).
Collect the logs in a file and attach the file to this issue for analysis (or look at them and see if it's clear what's going on -- maybe an authentication error, maybe a JavaScript error, etc.).

**Comment by qasim9872** [comment] 2021-04-29 18:26
Hi @sbordet 

Thanks for getting back so quickly.

I am connecting from a backend server to another backend server (GMS) using ComedD. Before importing the CometD library, I import the "cometd-nodejs-client" which will allow the CometD library to work on the backend.

In our case, with the same configurations; it happens once every few times. We have a load balancer that is routing between 4 CometD servers. If we stop the others, and keep one running, in that case, everything works as expected. We only see the 402 error when we load balance across 4 servers. Could that be the cause?

Thanks for sharing that information. Really appreciate it, I will follow the steps you have mentioned and get back with a log file.

Thanks,
Qasim

**Comment by sbordet** [comment] 2021-04-29 19:30
> We only see the 402 error when we load balance across 4 servers. Could that be the cause?

The load balancer must be sticky.

See this documentation, which is about the Oort cluster, but also applies to your case:
https://docs.cometd.org/current/reference/#_java_oort

**Comment by pmeister** [comment] 2021-06-28 17:19
Some of our customers have reported a similar problem with the connection dropping and getting no further events. Right now we're using an older version of the cometd dependency: 4.0.9. Have there been any fixes made in more recent versions which might help with this problem? @sbordet

**Comment by sbordet** [comment] 2021-06-29 14:03
@pmeister no, all reports of this kind so far turned out to be some misconfiguration of either the load balancer or the server.

I recommend to upgrade anyway, and if you still have the problem, provide more information.

**Comment by pmeister** [comment] 2021-06-29 14:08
@sbordet Interesting, thanks. Unfortunately, the server is out of our control. We're just a client subscribing to Salesforce CDC events using Java code based on [their EMP Connector example code](https://developer.salesforce.com/docs/atlas.en-us.change_data_capture.meta/change_data_capture/cdc_subscribe_emp_connector.htm). Is there anything you can refer me to which explains a typical server misconfiguration that we might be able to communicate to Salesforce support?

**Comment by sbordet** [comment] 2021-06-29 16:08
@pmeister sorry but while Salesforce CDC uses CometD we don't know their logic to, for example, kick out users or throttle them, etc. or even if they have such features.

You should ask the Salesforce CDC project, as the CometD project does not control the EMP connector code.

Since they are using CometD, if you can enable client-side DEBUG logging and report a debug log here, I may help you figure out what's happening; but then if it's a server explicit disconnection, or an EMP bug there is not much we can do.

Can you gather the DEBUG logs when you get these disconnections?

**Comment by sbordet** [comment] 2022-02-18 11:55
Closing as no further information was provided.

**Closed as completed by sbordet** 2022-02-18 11:55 UTC
