### ISSUE TITLE
How to completely disable binding to multicast address (in static-discovery mode)?

### ISSUE THREAD

**Issue by leopal77** [cometd/cometd#767] opened 2018-01-24 10:24 UTC
On one of our cluster setups we use static discovery, but we've seen that cometd still receives multicast messages coming from another setup (on the same network) that uses automatic discovery. 

It seems that by using static discovery (not using `OortMulticastServlet`) the only thing that is disabled is being advertised. Not receiving advertisements.

So in the logs of a SetupA-node we see:  `BayeuxAuthenticator - canSubscribe was hit from SetupB-<node-Ip>`

**Comment by sbordet** [comment] 2018-01-24 10:39
I don't understand what the problem is ?
Can you please reword by stating you exact setup, name the nodes, specify how each node is configured, what you expect to happen, and what happens instead ?

**Comment by leopal77** [comment] 2018-01-24 11:07
Let me explain.

We have two setups of our app in the same network. Let's name them setupA and setupB

SetupA consists of a single node ,let's call it **setupAnode1**. In this node cometd is configured to use `OortMulticastConfigServlet`. We only provide the `oort.url` parameter containing the **setupAnode1** ip. The rest configuration parameters are the default ones(including multicast address).

SetupB is again a cluster setup containing 2 nodes, let's refer to them as **setupBnode1** and **setupBnode2**. This setup uses `OortStaticConfigServlet` and in each node we provide the corresponding  `ort.url` and `ort.cloud`. We have implemented a custom `BayeuxAuthenticator ` which inform us about which node is trying to subscribe / publish to application channels. 

The point is that in logs of SetupB we receive requests(for subscription and publishing) from the setupAnode1. So we are wondering how we can prevent **setupAnode1** automatically discover setupB nodes.

**Comment by sbordet** [comment] 2018-01-25 14:52
The only way that the B cluster is aware of nodeA is that either you have configured by mistake the B cluster with the nodeA URL (or with a node that transitively knows nodeA), or you have by mistake the multicast component active also in the B cluster.

**Comment by leopal77** [comment] 2018-01-26 06:51
As for the multicast, **setupAnode1** uses `OortMulticastConfigServlet`. In servlet's configuration we have not added any oort multicast parameter(I am referring to `oort.multicast.groupAddress`) so as I can understand from the documentation,  the `239.255.0.1`(default) is used as multicast address in setupA.

Now in setupB, `OortStaticConfigServlet` is used for both nodes. In this setup, we also have not any `oort.multicast.groupAddress` added as oort servlet parameter. 

From the documentation it seems that `oort.multicast.groupAddress` parameter has effect only if `OortMulticastConfigServlet` is used. 

We have declared a multicast address only at application server's level(wildfly) in order to achieve communication between the nodes of clusterB.

**Comment by sbordet** [comment] 2018-02-12 13:08
Closed as requested in #768.

**Closed by sbordet** 2018-02-12 13:08 UTC
