### ISSUE TITLE
cometd-dojo not published on npm

### ISSUE THREAD

**Issue by NTARelix** [cometd/cometd#719] opened 2017-04-12 17:37 UTC
I'm working on a dojo project that requires cometd and we're beginning to use npm for dependencies and build scripts. There's another repo, https://github.com/cometd/cometd-dojo, that contains the exact files we need, but it is not published to npm. `cometd-dojo` is automatically updated via the release script in this repo. When the release script updates `cometd-dojo`, it dynamically creates the `package.json`, but never publishes. This seems like it would be the place to publish that repo to npmjs.org; perhaps with the `name` from `package.json` as `cometd-dojo` rather than `CometD`.

**Comment by sbordet** [comment] 2017-04-12 18:43
The `cometd-dojo` repo was requested by Dojo developers (way back) to be consumable via Git.

CometD is pushed in NPM as https://www.npmjs.com/package/cometd mirroring the repo `cometd-javascript`.

There is no explicit need for the Dojo bindings, you can use CometD with vanilla JS.

Have you tried to consume that NPM package ?

**Comment by NTARelix** [comment] 2017-04-12 18:54
I've looked at the `cometd` package on npmjs.org, but it doesn't contain the files I need without a moderate refactor of my codebase. The cometd files I'm using in my codebase today are the exact files found in the `cometd/cometd-dojo` repo.

**Comment by sbordet** [comment] 2017-04-12 19:05
I'm not sure I understand. `cometd-dojo` files are consumed via AMD, so it should be just a matter of aliasing.

Furthermore, since `cometd-dojo` is only AMD, can't really be deployed in NPM as it would break people that expect NPM packages to work fine in Node and CommonJS.

Can you detail how you use the `cometd-dojo` files (that BTW are just thin wrappers around those published to NPM), and why the NPM package does not work for you ?

**Comment by NTARelix** [comment] 2017-04-12 20:56
Here are the JS files available in the `cometd` npm package:

- `AckExtension.js`
- `BinaryExtension.js`
- `ReloadExtension.js`
- `TimeStampExtension.js`
- `TimeSyncExtension.js`
- `cometd.js`

Of all those files, `cometd.js` is the only file that has the code I need. The exported value of this module is an object with CometD constructors:

```
return {
    CometD: CometD,
    Transport: Transport,
    RequestTransport: RequestTransport,
    LongPollingTransport: LongPollingTransport,
    CallbackPollingTransport: CallbackPollingTransport,
    WebSocketTransport: WebSocketTransport,
    Utils: Utils,
    Z85: Z85
};
```

There are a lot more files bundled with `cometd/cometd-dojo`, but the main one would need to import for everything to work in my codebase would be `~/cometd/main.js` which exports an instance of the CometD constructor (the same one inside the object exported from `cometd.js` in the `cometd` npm package).

Because of the inconsistent exported values between `cometd` and `cometd-dojo`, it's not possible for `cometd` to work as a drop-in replacement for `cometd-dojo`.

There are 2 workarounds to this problem I can think of:

1. Use some build-magic to alias `dojox/cometd` to a custom module that imports `cometd-dojo` and exports an instance of the `CometD` class.
2. Refactor _every_ import of `dojox/cometd` so that they create their own instances.

I would rather not introduce additional complexity into the build and, while a refactor might not be difficult, it also introduces unnecessary complexity.

The alternative I'm suggesting would involve changing the `name` from `cometd-dojo`'s `package.json` to `cometd-dojo`, then publishing the resulting module to npm so I could add `cometd-dojo` to my `package.json` and do an easy _find & replace all_ so all my imports reference `cometd-dojo`. It's a much cleaner solution on my end and _should_ only be a few lines changed in `cometd`'s `release.sh` file.

**Comment by sbordet** [comment] 2017-06-06 13:56
Sorry, I am lost of what the problem is.

Can you show me an example of what would not work, and the steps necessary to reproduce the problem ?

**Comment by sbordet** [comment] 2018-09-04 09:35
Closing as now there is a full NodeJS implementation of CometD, client and server on NPM.

https://www.npmjs.com/package/cometd
https://www.npmjs.com/package/cometd-nodejs-client
https://www.npmjs.com/package/cometd-nodejs-server

**Closed by sbordet** 2018-09-04 09:35 UTC
