### ISSUE TITLE
Subscriber doesn't receive event

### ISSUE THREAD

**Issue by rahulcodewiz** [cometd/cometd#1018] opened 2021-03-29 15:52 UTC
I am facing issue with client which connect server over the long-polling transport. There is unknown scenario when Bayeux client and channels shows as CONNECTED and subscriber(PEListenerKafkaPublisher) stop receiving event. At the same time we see events are reaching to extension (ReplayExtension).

```
platformevent.pull.listener.SFDCPlatformEventListenerV2,EnhancedBayeuxClient@762f062b[281fubf9u3oc3xy1mhi0kpswuiid][SessionState@50e82092[CONNECTED]], dump:EnhancedBayeuxClient@762f062b[281fubf9u3oc3xy1mhi0kpswuiid][SessionState@50e82092[CONNECTED]]
    +> AttributesMap@496367f2
    |  +> null
    +> extensions size=1
    |  +> platformevent.pull.extension.ReplayExtension@6101e9c5
    +> channels size=8
       +> /event/ae_spark__TEL_Bulk_Change__e
       |  +> listeners size=0
       |  +> subscribers size=1
       |     +> subscriber.PEListenerKafkaPublisher@2bf94401
       +> /meta/*
       |  +> listeners size=0
       |  +> subscribers size=0
       +> /meta/**
       |  +> listeners size=0
       |  +> subscribers size=0
       +> /meta/connect
       |  +> listeners size=1
       |  |  +> platformevent.pull.listener.PullAuthFailureListener@7fec5ba4
       |  +> subscribers size=0
       +> /meta/disconnect
       |  +> listeners size=0
       |  +> subscribers size=0
       +> /meta/handshake
       |  +> listeners size=0
       |  +> subscribers size=0
       +> /meta/subscribe
       |  +> listeners size=1
       |  |  +> platformevent.pull.listener.EnhancedBayeuxClient$$Lambda$1240/918157032@306ad64
       |  +> subscribers size=0
       +> /meta/unsubscribe
          +> listeners size=1
          |  +> platformevent.pull.listener.EnhancedBayeuxClient$$Lambda$1239/617777499@4a59da25
          +> subscribers size=0
    key: +- bean, += managed, +~ unmanaged, +? auto, +: iterable, +] array, +@ map, +> undefined,
    Extensions:[platformevent.pull.extension.ReplayExtension@6101e9c5]
    HttpClient: HttpClient@5b519f20{STARTED}
    2021-03-27 21:17:08.734  INFO 67 --- [qtp561448546-42] c.a.s.p.p.p.l.EnhancedBayeuxClient       : Recived lstn:{clientId=281fubf9u3oc3xy1mhi0kpswuiid, channel=/meta/subscribe, id=1077, subscription=/event/ae_spark__TEL_Bulk_Change__e, successful=true}
```

I have a logic in PullAuthFailureListener which restart Bayeux Client when Message is unsuccessful. Restart Steps are:

- Unsubscribe all channels.
- Disconnect Bayeux client.
- Handshake again
- Register channel/subscriber (/event/ae_spark__TEL_Bulk_Change__e)

Any suggestions what might be preventing events to reach subscriber or any suggestions to troubleshoot this further?

**Comment by sbordet** [comment] 2021-03-29 21:03
There is too much that is not CometD but application code, or a library that wraps CometD, and likely the problem is there and not in CometD.

The `ReplayExtension` is not part of CometD, so I would look into that first: if event arrive there but not to the application, then it means that the extension is blocking the events.

**Comment by sbordet** [comment] 2021-04-29 09:14
Closing as no further information was given.

**Closed as completed by sbordet** 2021-04-29 09:14 UTC
