### ISSUE TITLE
Not able run the cometd demo 

### ISSUE THREAD

**Issue by saysiva** [cometd/cometd#642] opened 2016-03-17 09:30 UTC
Tried to run the demos using this documentation (section : 3.3.1)
https://docs.cometd.org/current/reference/#_installation

Getting some error like this.

Caused by: 
java.lang.ClassNotFoundException: org.eclipse.jetty.io.SelectorManager$ManagedSelector$Stop
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.doStop(SelectorManager.java:433)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at org.eclipse.jetty.io.SelectorManager.doStop(SelectorManager.java:277)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:143)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:162)
	at org.eclipse.jetty.websocket.client.io.ConnectionManager.doStop(ConnectionManager.java:217)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:143)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:162)
	at org.eclipse.jetty.websocket.client.WebSocketClient.doStop(WebSocketClient.java:279)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:143)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:162)
	at org.eclipse.jetty.websocket.jsr356.ClientContainer.doStop(ClientContainer.java:195)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at org.eclipse.jetty.util.thread.ShutdownThread.run(ShutdownThread.java:138)
2016-03-17 02:18:44.667:WARN:oejuc.AbstractLifeCycle:Thread-1: FAILED org.eclipse.jetty.websocket.jsr356.ClientContainer@6a960bb5: java.lang.NoClassDefFoundError: org/eclipse/jetty/io/SelectorManager$ManagedSelector$Stop

**Comment by sbordet** [comment] 2016-03-17 10:03
What Jetty version are you using ? You need Jetty 9.2.x.

**Comment by saysiva** [comment] 2016-03-17 10:10
Its the embedded version within it.  

 <jetty-version>9.2.14.v20151106</jetty-version>

Not downloaded anything explictly.

**Comment by saysiva** [comment] 2016-03-17 10:26
Tried your solution also from below issue. Its not working in my machine.

https://github.com/cometd/cometd/issues/622

**Comment by sbordet** [comment] 2016-03-17 11:09
You likely have some classpath issue.

To build CometD 3.0.x be sure to use JDK 7 and a recent version of Maven, and you should be good.

If not, please post _exact_ steps to reproduce.

Thanks !

**Comment by sbordet** [comment] 2016-04-06 19:12
Works for me, closing as non reproducible. Please reopen if you have more information to reproduce (please, _exact_ steps). 

Thanks !

**Closed by sbordet** 2016-04-06 19:12 UTC

**Comment by gregory-chapman** [comment] 2016-04-30 00:19
I had the same issue. There are a few causes. 

First, I had a tomcat instance on port 8080 and when Jetty came up it threw this exception in 3.0.9. In 3.0.8 it gave output that described the port was taken.

Second, an older version of maven caused the issue as well. When updating maven it worked.

Make sure your maven is up-to-date and nothing is currently on your port. There probably is a bug in 3.0.9 that is exposed by these conditions.
