### ISSUE TITLE
remote archetype catalog download not working from maven command

### ISSUE THREAD

**Issue by mikemorrell2** [cometd/cometd#716] opened 2017-03-28 18:34 UTC
I am starting to tryout cometd following the primer instructions in the documentation. When I use the following command, it does not find the remote archetype catalog.

mvn archetype:generate -DarchetypeCatalog=http://cometd.org

**Comment by sbordet** [comment] 2017-03-30 08:02
Duplicate of #711. Online documentation updated.

**Closed by sbordet** 2017-03-30 08:02 UTC
