### ISSUE TITLE
Oort map sync issues

### ISSUE THREAD

**Issue by fdummert** [cometd/cometd#643] opened 2016-03-18 14:13 UTC
I have two nodes A and B with a shared Oort map. When restarting one node, the maps go occasionally out of sync. There seem to be multiple different error scenarios, which are listed below. All of them are related to version mismatches when putting local or remote map keys and identifiable by "Skipped local|remote map (...)" log entries.

1) -- removed, invalid assumption

2) Concurrency issues when adding own data to the map. Are Oort objects meant to be thread-safe?
[log-2.txt](https://github.com/cometd/cometd/files/179784/log-2.txt)
Two different threads (message listeners of two concurrent requests) are trying to write data to the map. Thread 24 starts by incrementing the version to 1. Thread 31 increments to 2. Now thread 31 writes the data prior to thread 24, and the Oort map skips the write attempt due to version mismatch

3) (maybe same as 2)) - I've configured Bayeux with the ack extension. Oort is configured with the ack extension. The Oort map is configured by adding the ack extension (is this necessary at all?): 
`map.getLocalSession().addExtension(new AckExtension());`
On node B, I'm seeing two remote map puts out of order (version 2 before version 1), although they were put into the map in correct order (but from different threads - which turn this probably just into a variant of 2)).  
[log-3b.txt](https://github.com/cometd/cometd/files/179897/log-3b.txt)

Conclusion: there are concurrency issues. The implementation of OortMap/OortObject looks like thread-safety was one design goal. But then the access has still to be locked more coarse-grained. While you could argue that local map puts from different threads should be synchronized by the invoker, the question remains what to do for remote map puts? Are they guaranteed to be executed in the same thread? Probably not. Then this should be addressed by the implementation, right?

**Comment by sbordet** [comment] 2016-03-24 11:42
@fdummert you are right that `OortObject` and subclasses were intended to be thread-safe, but they were not.

I have reworked the implementation to make it thread-safe and by handling out-of-order updates in remote nodes.

Will be great if you can test the latest code in branch `3.0.x`.

Thanks !

**Comment by sbordet** [comment] 2016-04-05 17:15
@fdummert were you able to test this change ?

Thanks !

**Comment by fdummert** [comment] 2016-04-06 08:50
Hi Simone,

sorry, not yet, currently very busy. Maybe I can find a timeslot tomorrow,
worst case next week. But I'm looking forward to remove my synchronized()
workaround soon!

Best Regards,
Florian

2016-04-05 19:15 GMT+02:00 Simone Bordet <notifications@github.com>:

**Comment by fdummert** [comment] 2016-04-07 10:40
Hi Simone,

wow, that was a major rewrite... I *think* I experienced a dead lock with the new implementation, however. I found one thread hanging in OortObject line 783:
```
OortObject$Processor.await() line: 783
OortObject$Processor.process(boolean, ServerMessage) line: 736
OortObject$Processor.access$1(OortObject$Processor, boolean, ServerMessage) line: 727
OortObject$BroadcastListener.onMessage(ServerSession, ServerChannel, ServerMessage$Mutable) line: 699	
BayeuxServerImpl.notifyOnMessage(ServerChannel$MessageListener, ServerSession, ServerChannel, ServerMessage$Mutable) line: 991
BayeuxServerImpl.notifyListeners(ServerSessionImpl, ServerChannelImpl, Mutable, List<String>) line: 951
BayeuxServerImpl.doPublish(ServerSessionImpl, ServerChannelImpl, ServerMessage$Mutable) line: 878
ServerChannelImpl.publish(Session, ServerMessage$Mutable) line: 331
ServerChannelImpl.publish(Session, Object) line: 341
ServiceRegistry$OortServiceProviderMap(OortMap<K,V>).putAndShare(K, V) line: 110```

What could have gone wrong here?

Best Regards,
Florian

**Comment by sbordet** [comment] 2016-04-07 12:03
@fdummert 

it's not a deadlock, it's just a way to serialize the processing of `putAndShare()` calls.

Ideally, `await()` should last very little time.

You have a case where the thread is stuck waiting for a long time ?

**Comment by fdummert** [comment] 2016-04-07 12:13
Yes, the thread seems to be stuck here forever. But putAndShare should not really block indefinitely, I suppose.

**Comment by sbordet** [comment] 2016-04-07 13:15
I fail to see how this can happen... can you reproduce ? DEBUG logs ?

**Comment by fdummert** [comment] 2016-04-07 13:45
Yes, I can, hope the log output helps:
```
2016-04-07 14:07:24,630 [main] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Set local {oort.info.url=http://localhost:8080/comet-server/cometd, oort.info.object={}, oort.info.name=services, oort.info.version=0}
2016-04-07 14:07:24,646 [main] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Received broadcast {data={oort.info.url=http://localhost:8080/comet-server/cometd, oort.info.object={}, oort.info.name=services, oort.info.version=0}, channel=/oort/objects/services}
2016-04-07 14:07:24,648 [main] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Skipped local update of {oort.info.url=http://localhost:8080/comet-server/cometd, oort.info.object={}, oort.info.name=services, oort.info.version=0} with {oort.info.url=http://localhost:8080/comet-server/cometd, oort.info.object={}, oort.info.name=services, oort.info.version=0}
2016-04-07 14:07:24,654 [main] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Dequeued update version=0, data=null
2016-04-07 14:07:24,657 [main] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - OortServiceProviderMap[services]@http://localhost:8080/comet-server/cometd started
2016-04-07 14:07:24,667 [main] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Sharing map put {oort.info.url=http://localhost:8080/comet-server/cometd, oort.info.object={oort.map.value=cd929ea0-8dfb-4fdf-ac6a-4f7d442fb8ec [/service/core/server/ComponentManager/1.0.0], oort.map.key=cd929ea0-8dfb-4fdf-ac6a-4f7d442fb8ec}, oort.info.name=services, oort.info.action=oort.map.put, oort.info.version=1, oort.info.type=oort.map.entry}
2016-04-07 14:07:24,669 [main] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Received broadcast {data={oort.info.url=http://localhost:8080/comet-server/cometd, oort.info.object={oort.map.value=cd929ea0-8dfb-4fdf-ac6a-4f7d442fb8ec [/service/core/server/ComponentManager/1.0.0], oort.map.key=cd929ea0-8dfb-4fdf-ac6a-4f7d442fb8ec}, oort.info.name=services, oort.info.action=oort.map.put, oort.info.version=1, oort.info.type=oort.map.entry}, channel=/oort/objects/services}
2016-04-07 14:07:24,670 [main] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Local map oort.map.put of (cd929ea0-8dfb-4fdf-ac6a-4f7d442fb8ec=null->cd929ea0-8dfb-4fdf-ac6a-4f7d442fb8ec [/service/core/server/ComponentManager/1.0.0])
2016-04-07 14:07:24,749 [main] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Sharing map put {oort.info.url=http://localhost:8080/comet-server/cometd, oort.info.object={oort.map.value=bd2a0a44-4c7e-494f-85e0-443f6e72d226 [/service/core/server/Authentication/1.0.0], oort.map.key=bd2a0a44-4c7e-494f-85e0-443f6e72d226}, oort.info.name=services, oort.info.action=oort.map.put, oort.info.version=2, oort.info.type=oort.map.entry}
2016-04-07 14:07:24,749 [main] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Received broadcast {data={oort.info.url=http://localhost:8080/comet-server/cometd, oort.info.object={oort.map.value=bd2a0a44-4c7e-494f-85e0-443f6e72d226 [/service/core/server/Authentication/1.0.0], oort.map.key=bd2a0a44-4c7e-494f-85e0-443f6e72d226}, oort.info.name=services, oort.info.action=oort.map.put, oort.info.version=2, oort.info.type=oort.map.entry}, channel=/oort/objects/services}
2016-04-07 14:07:24,749 [main] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Local map oort.map.put of (bd2a0a44-4c7e-494f-85e0-443f6e72d226=null->bd2a0a44-4c7e-494f-85e0-443f6e72d226 [/service/core/server/Authentication/1.0.0])
2016-04-07 14:07:24,749 [main] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Sharing map put {oort.info.url=http://localhost:8080/comet-server/cometd, oort.info.object={oort.map.value=af3ec8cf-b141-495a-912b-03d3e40b33bc [/service/core/server/PullAuth/1.0.0], oort.map.key=af3ec8cf-b141-495a-912b-03d3e40b33bc}, oort.info.name=services, oort.info.action=oort.map.put, oort.info.version=3, oort.info.type=oort.map.entry}
2016-04-07 14:07:24,750 [main] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Received broadcast {data={oort.info.url=http://localhost:8080/comet-server/cometd, oort.info.object={oort.map.value=af3ec8cf-b141-495a-912b-03d3e40b33bc [/service/core/server/PullAuth/1.0.0], oort.map.key=af3ec8cf-b141-495a-912b-03d3e40b33bc}, oort.info.name=services, oort.info.action=oort.map.put, oort.info.version=3, oort.info.type=oort.map.entry}, channel=/oort/objects/services}
2016-04-07 14:07:24,750 [main] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Local map oort.map.put of (af3ec8cf-b141-495a-912b-03d3e40b33bc=null->af3ec8cf-b141-495a-912b-03d3e40b33bc [/service/core/server/PullAuth/1.0.0])
2016-04-07 14:07:24,750 [main] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Sharing map put {oort.info.url=http://localhost:8080/comet-server/cometd, oort.info.object={oort.map.value=68678382-f066-46cd-871e-9beeed741f6e [/service/core/server/Service/1.0.0], oort.map.key=68678382-f066-46cd-871e-9beeed741f6e}, oort.info.name=services, oort.info.action=oort.map.put, oort.info.version=4, oort.info.type=oort.map.entry}
2016-04-07 14:07:24,750 [main] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Received broadcast {data={oort.info.url=http://localhost:8080/comet-server/cometd, oort.info.object={oort.map.value=68678382-f066-46cd-871e-9beeed741f6e [/service/core/server/Service/1.0.0], oort.map.key=68678382-f066-46cd-871e-9beeed741f6e}, oort.info.name=services, oort.info.action=oort.map.put, oort.info.version=4, oort.info.type=oort.map.entry}, channel=/oort/objects/services}
2016-04-07 14:07:24,750 [main] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Local map oort.map.put of (68678382-f066-46cd-871e-9beeed741f6e=null->68678382-f066-46cd-871e-9beeed741f6e [/service/core/server/Service/1.0.0])
2016-04-07 14:07:24,861 [main] INFO  org.springframework.web.context.ContextLoader - Root WebApplicationContext: initialization completed in 1938 ms
2016-04-07 14:07:24.888:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@4f4c4b1a{/comet-server,file:/home/flo/Development/workspaceSE/comet-server/web/,AVAILABLE}{/home/flo/Development/workspaceSE/comet-server/web}
2016-04-07 14:07:24.897:INFO:oejs.ServerConnector:main: Started ServerConnector@71e35c4{HTTP/1.1}{0.0.0.0:8080}
2016-04-07 14:07:24.900:INFO:oejs.Server:main: Started @5612ms
-------------------------------------------------
Jetty startup finished in 5,6 s.
Used memory: 32,5 MB of 325,5 MB (1,7 GB maximum)
Console available: type "help".
-------------------------------------------------
2016-04-07 14:07:28,178 [qtp610984013-47] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Oort http://localhost:8082/comet-server/cometd joined
2016-04-07 14:07:28,178 [qtp610984013-47] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Pushing (to http://localhost:8082/comet-server/cometd): {oort.info.url=http://localhost:8080/comet-server/cometd, oort.info.object={68678382-f066-46cd-871e-9beeed741f6e=68678382-f066-46cd-871e-9beeed741f6e [/service/core/server/Service/1.0.0], cd929ea0-8dfb-4fdf-ac6a-4f7d442fb8ec=cd929ea0-8dfb-4fdf-ac6a-4f7d442fb8ec [/service/core/server/ComponentManager/1.0.0], af3ec8cf-b141-495a-912b-03d3e40b33bc=af3ec8cf-b141-495a-912b-03d3e40b33bc [/service/core/server/PullAuth/1.0.0], bd2a0a44-4c7e-494f-85e0-443f6e72d226=bd2a0a44-4c7e-494f-85e0-443f6e72d226 [/service/core/server/Authentication/1.0.0]}, oort.info.name=services, oort.info.version=4}
2016-04-07 14:07:28,194 [qtp610984013-18] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Oort http://localhost:8083/comet-server/cometd joined
2016-04-07 14:07:28,194 [qtp610984013-18] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Pushing (to http://localhost:8083/comet-server/cometd): {oort.info.url=http://localhost:8080/comet-server/cometd, oort.info.object={68678382-f066-46cd-871e-9beeed741f6e=68678382-f066-46cd-871e-9beeed741f6e [/service/core/server/Service/1.0.0], cd929ea0-8dfb-4fdf-ac6a-4f7d442fb8ec=cd929ea0-8dfb-4fdf-ac6a-4f7d442fb8ec [/service/core/server/ComponentManager/1.0.0], af3ec8cf-b141-495a-912b-03d3e40b33bc=af3ec8cf-b141-495a-912b-03d3e40b33bc [/service/core/server/PullAuth/1.0.0], bd2a0a44-4c7e-494f-85e0-443f6e72d226=bd2a0a44-4c7e-494f-85e0-443f6e72d226 [/service/core/server/Authentication/1.0.0]}, oort.info.name=services, oort.info.version=4}
2016-04-07 14:07:28,250 [qtp610984013-47] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Received service {clientId=a1wvjqis8y01s1uml9ghtdop9x, data={oort.info.url=http://localhost:8082/comet-server/cometd, oort.info.object={097e9df1-4f4d-4519-922c-94751db72a8e={uuid=097e9df1-4f4d-4519-922c-94751db72a8e, oortUrl=null, type=REMOTE, services=[{owner=ect, application=App, name=test, version=1.0.0, securityPropertyNames=[customerId], exposure=null, pattern=null, provider=097e9df1-4f4d-4519-922c-94751db72a8e, internalVersion=1.0.0, channel=/service/ect/App/test/1, locked=false}, {owner=ect, application=App, name=VabApi, version=1.0.0, securityPropertyNames=[customerId, userName], exposure=null, pattern=null, provider=097e9df1-4f4d-4519-922c-94751db72a8e, internalVersion=1.0.0, channel=/service/ect/App/VabApi/1, locked=false}, {owner=ect, application=App, name=VAB_Form, version=1.0.0, securityPropertyNames=[userId], exposure=null, pattern=null, provider=097e9df1-4f4d-4519-922c-94751db72a8e, internalVersion=1.0.0, channel=/service/ect/App/VAB_Form/1, locked=false}, {owner=ect, application=App, name=authenticationProvider, version=1.0.0, securityPropertyNames=[], exposure=null, pattern=null, provider=097e9df1-4f4d-4519-922c-94751db72a8e, internalVersion=1.0.0, channel=/service/ect/App/authenticationProvider/1, locked=false}]}, bfcc2e94-3dfd-4a5b-bcce-eb40b70d072d={uuid=bfcc2e94-3dfd-4a5b-bcce-eb40b70d072d, oortUrl=null, type=LOCAL_CLIENT, services=[{owner=core, application=server, name=Authentication, version=1.0.0, securityPropertyNames=[], exposure=null, pattern=null, provider=bfcc2e94-3dfd-4a5b-bcce-eb40b70d072d, internalVersion=1.0.0, channel=/service/core/server/Authentication/1, locked=false}]}, 8469d0cb-ccbc-43e2-a31f-3f12a7d45535={uuid=8469d0cb-ccbc-43e2-a31f-3f12a7d45535, oortUrl=null, type=LOCAL_LIGHT, services=[{owner=core, application=server, name=PullAuth, version=1.0.0, securityPropertyNames=[], exposure=[], pattern=null, provider=8469d0cb-ccbc-43e2-a31f-3f12a7d45535, internalVersion=1.0.0, channel=/service/core/server/PullAuth/1, locked=false}]}, c5f0b515-58c7-4681-b7ea-285b7bff88f8={uuid=c5f0b515-58c7-4681-b7ea-285b7bff88f8, oortUrl=null, type=LOCAL_CLIENT, services=[{owner=core, application=server, name=Service, version=1.0.0, securityPropertyNames=[], exposure=null, pattern=null, provider=c5f0b515-58c7-4681-b7ea-285b7bff88f8, internalVersion=1.0.0, channel=/service/core/server/Service/1, locked=false}]}, a5f13615-3ab7-479f-8c17-32e697b0d3c3={uuid=a5f13615-3ab7-479f-8c17-32e697b0d3c3, oortUrl=null, type=LOCAL_LIGHT, services=[{owner=core, application=server, name=ComponentManager, version=1.0.0, securityPropertyNames=[], exposure=[], pattern=null, provider=a5f13615-3ab7-479f-8c17-32e697b0d3c3, internalVersion=1.0.0, channel=/service/core/server/ComponentManager/1, locked=false}]}}, oort.info.name=services, oort.info.version=5, oort.info.peer=http://localhost:8080/comet-server/cometd}, channel=/service/oort/objects/services, id=72}
2016-04-07 14:07:28,248 [qtp610984013-18] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Received service {clientId=81cymk0hiurhn1q4ry1nnesf61, data={oort.info.url=http://localhost:8083/comet-server/cometd, oort.info.object={72d2850f-a584-4403-acfb-153dec6b621c={uuid=72d2850f-a584-4403-acfb-153dec6b621c, oortUrl=null, type=LOCAL_CLIENT, services=[{owner=core, application=server, name=Authentication, version=1.0.0, securityPropertyNames=[], exposure=null, pattern=null, provider=72d2850f-a584-4403-acfb-153dec6b621c, internalVersion=1.0.0, channel=/service/core/server/Authentication/1, locked=false}]}, 8106bb18-2fe8-4986-945a-a56659045c49={uuid=8106bb18-2fe8-4986-945a-a56659045c49, oortUrl=null, type=LOCAL_LIGHT, services=[{owner=core, application=server, name=ComponentManager, version=1.0.0, securityPropertyNames=[], exposure=[], pattern=null, provider=8106bb18-2fe8-4986-945a-a56659045c49, internalVersion=1.0.0, channel=/service/core/server/ComponentManager/1, locked=false}]}, d4f4ed8e-7f18-48d6-af62-8ac67a538305={uuid=d4f4ed8e-7f18-48d6-af62-8ac67a538305, oortUrl=null, type=LOCAL_LIGHT, services=[{owner=core, application=server, name=PullAuth, version=1.0.0, securityPropertyNames=[], exposure=[], pattern=null, provider=d4f4ed8e-7f18-48d6-af62-8ac67a538305, internalVersion=1.0.0, channel=/service/core/server/PullAuth/1, locked=false}]}, af9b6912-3524-43f6-8f5b-7c55cba4b102={uuid=af9b6912-3524-43f6-8f5b-7c55cba4b102, oortUrl=null, type=LOCAL_CLIENT, services=[{owner=core, application=server, name=Service, version=1.0.0, securityPropertyNames=[], exposure=null, pattern=null, provider=af9b6912-3524-43f6-8f5b-7c55cba4b102, internalVersion=1.0.0, channel=/service/core/server/Service/1, locked=false}]}}, oort.info.name=services, oort.info.version=4, oort.info.peer=http://localhost:8080/comet-server/cometd}, channel=/service/oort/objects/services, id=64}
2016-04-07 14:07:28,264 [qtp610984013-49] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Sharing map put {oort.info.url=http://localhost:8080/comet-server/cometd, oort.info.object={oort.map.value=c6950c84-6848-4060-90a2-dbad376a62dc [/service/ect/-/authenticationProvider/1.0.0], oort.map.key=c6950c84-6848-4060-90a2-dbad376a62dc}, oort.info.name=services, oort.info.action=oort.map.put, oort.info.version=5, oort.info.type=oort.map.entry}
2016-04-07 14:07:28,264 [qtp610984013-49] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Received broadcast {data={oort.info.url=http://localhost:8080/comet-server/cometd, oort.info.object={oort.map.value=c6950c84-6848-4060-90a2-dbad376a62dc [/service/ect/-/authenticationProvider/1.0.0], oort.map.key=c6950c84-6848-4060-90a2-dbad376a62dc}, oort.info.name=services, oort.info.action=oort.map.put, oort.info.version=5, oort.info.type=oort.map.entry}, channel=/oort/objects/services}
2016-04-07 14:07:28,316 [qtp610984013-47] DEBUG OortServiceProviderMap.http_localhost_8080_comet_server_cometd.services - Performed remote update of null with {oort.info.url=http://localhost:8082/comet-server/cometd, oort.info.peer=http://localhost:8080/comet-server/cometd, oort.info.object={097e9df1-4f4d-4519-922c-94751db72a8e=097e9df1-4f4d-4519-922c-94751db72a8e [/service/ect/App/test/1.0.0, /service/ect/App/VabApi/1.0.0, /service/ect/App/VAB_Form/1.0.0, /service/ect/App/authenticationProvider/1.0.0], bfcc2e94-3dfd-4a5b-bcce-eb40b70d072d=bfcc2e94-3dfd-4a5b-bcce-eb40b70d072d [/service/core/server/Authentication/1.0.0], 8469d0cb-ccbc-43e2-a31f-3f12a7d45535=8469d0cb-ccbc-43e2-a31f-3f12a7d45535 [/service/core/server/PullAuth/1.0.0], c5f0b515-58c7-4681-b7ea-285b7bff88f8=c5f0b515-58c7-4681-b7ea-285b7bff88f8 [/service/core/server/Service/1.0.0], a5f13615-3ab7-479f-8c17-32e697b0d3c3=a5f13615-3ab7-479f-8c17-32e697b0d3c3 [/service/core/server/ComponentManager/1.0.0]}, oort.info.name=services, oort.info.version=5}
```
In this case, the thread [qtp610984013-49] got stuck with the exact same stack as given above, the last debug statement was "Received broadcast..."

**Comment by sbordet** [comment] 2016-04-07 13:52
Looking... can you please take a JVM thread dump (`ctrl + \`) ? You can attach it here as a file. Thanks !

**Comment by fdummert** [comment] 2016-04-07 14:13
Hi Simone,

here the thread dump: [thread-dump.txt](https://github.com/cometd/cometd/files/208527/thread-dump.txt)

Note: you'll see other locks. I've got an own, more complex data structure sitting on top of the Oort map, "ServiceRegistry", which uses Read/Write locks to protect against concurrent write access. As the underlying Oort map blocks, you'll see other threads waiting, too...

Best Regards,
Florian

**Comment by sbordet** [comment] 2016-04-08 07:22
@fdummert,

the problem is that you are holding a lock to `ServiceRegistry` both when receiving messages and when publishing messages.

However, CometD should be transparent if applications do this... I'll try to come up with a solution, but I'm afraid it will require an API change.

Do you ever use the return value of `OortMap.putAndShare()` ?

**Comment by fdummert** [comment] 2016-04-08 12:59
Hi Simone, 

I know I'm locking myself with the read/write locks, as the Oort map does not return, but are you saying I'm blocking implicitly a thread that is meant to release your implementation from its wait state? Does it mean that putAndShare should be executed in a separate thread? Well, I do not use any return values of put/remove-AndShare, but I'm probably not the only person out there using Oort maps... am I :-) ?
I can still try to run these methods in separate threads and see what happens.

Best Regards,
Florian

**Comment by sbordet** [comment] 2016-04-08 13:43
Florian,

it is a mixed scenario. The CometD contract for listeners is that they must not block. Using locks inside a CometD listener is "dangerous" in the sense that if the code blocks, you are also blocking the CometD processing. Blocking the CometD processing means blocking the `/meta/connect` message processing, etc. which is vital for the correct functioning of CometD.

From your stack traces I can see you are doing in one thread:

```
<cometd>
  SecurityPolicy.canHandshake
    ServiceRegistry.lock
      OortMap.putAndShare
```

and in another thread:

```
<cometd>
  OortMap.notifyEntryPut
    ServiceRegistry.lock
```    

The "bad" thing is that you are calling `OortMap.putAndShare()` while holding a lock.
Another "bad" thing is that you have this single global lock that is acquired from many different code paths, which probably limits your scalability.

Now, I do realize that the deadlock you are experiencing is unexpected from the point of view of an application developer. CometD must not be so delicate that if you call `putAndShare()` with a lock held, then the system deadlocks. So this is definitely a CometD bug.

Unfortunately the deadlock traces back to the fact that `putAndShare()` and similar methods return a value. In order to return a value CometD needs to block a little, and this interacts badly with your application locking.

What I am doing is to offer you an asynchronous API for `putAndShare()` and deprecating the old one, so that you will be able to keep your locking as is and CometD won't need to block, resolving the issue.

Stay tuned.

**Comment by fdummert** [comment] 2016-04-11 08:22
Hi Simone,

thanks a lot for your valuable input! Fortunately, we a writing very rarely to the service registry (mostly on node startup, and on rare occasions during runtime). Almost all access to the service registry is read access during runtime. So I'm fairly confident that Read/WriteLocks should impose no scalability issue in practice. However, you are raising one issue regarding handshake/authentication, which might be of general interest, so I've opened an extra forum thread for this one: https://groups.google.com/forum/#!topic/cometd-users/lElqbJ4lLdM

And thanks for tackling this issue!

Best Regards,
Florian

**Comment by sbordet** [comment] 2016-04-28 11:59
@fdummert after many rewrites, I think the latest code is good in that it fixes the concurrency issues and introduces async methods that you can use in your code, deprecating the old ones.

Would be great if you can test it out.

Thanks !

**Comment by fdummert** [comment] 2016-05-02 07:38
Hi Simone,
the tests done so far look really promising. I'm pretty confident the issue has now been fixed.
Thanks a lot,
Florian

**Comment by sbordet** [comment] 2016-05-02 14:07
@fdummert

For completeness, you should now use the new async methods, e.g. 

```java
OortMap.putAndShare(key, value, new Result() { ... });
```

If you are not interested in the result, you can pass in `null`:

```java
OortMap.putAndShare(key, value, null);
```

Note that when the method returns it is not guaranteed that the key and value are in the map.
It is guaranteed only when the `Result` is notified.

By using the async version of these methods you should be safe with your application locking.

**Closed by sbordet** 2016-05-02 14:07 UTC
Labels: module: java-oort, priority: normal, type: bug, version: 3.0.9
